### PR TITLE
DSC_ImportPfx: Update private key import location for LocalMachine using Import-PfxCertificateEx

### LINKED ISSUE #248: DSC_PfxImport:'Import-PfxCertificateEx' function handles private keys differently then 'Import-PfxCertificate' cmdlet
#### Details of the scenario you tried and the problem that is occurring
Importing PFX certificates to the local machine certificate path and the resource uses the function 'Import-PfxCertificateEx' from the common module results in the private key being installed in the users key store location rather than the machine path.  The result of using the native 'Import-PfxCertificate' cmdlet is that the private key is stored in the same path as the public key import location.

Example results of importing with Import-PfxCertificateEx:
(Importing to cert:\currentuser\my) Private key is stored c:\users\<user>\AppData\LocalLow\Microsoft\Crypto
(Importing to cert:\localmachine\my) Private key is stored c:\users\<user>\AppData\LocalLow\Microsoft\Crypto

Example results of importing with Import-PfxCertificate:
(Importing to cert:\currentuser\my) Private key is stored c:\users\<user>\AppData\LocalLow\Microsoft\Crypto
(Importing to cert:\localmachine\my) Private key is stored C:\ProgramData\Microsoft\Crypto

The key store location for private keys should match between these two functions.  

#### Verbose logs showing the problem

#### Suggested solution to the issue
The fix would be to set the x509 flag during import to machinekey path for localmachine keys.  No change for currentuser path key imports.

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                                                                
PSVersion                      5.1.14393.3866                                                                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                              
BuildVersion                   10.0.14393.3866                                                                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                  
SerializationVersion           1.1.0.1 


#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by 39Delta**
#### Pull Request (PR) description
Importing PFX certificates to the local machine certificate path and the resource uses the function 'Import-PfxCertificateEx' from the common module results in the private key being installed in the users key store location rather than the machine path. The result of using the native 'Import-PfxCertificate' cmdlet is that the private key is stored in the same path as the public key import location.

#### This Pull Request (PR) fixes the following issues
    - Fixes #248

#### Task list
- [x] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/249)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I've submitted the fix for the CI: https://github.com/dsccommunity/CertificateDsc/pull/251 - Once that PR is through then you can rebase onto it and we'll get this merged.

**Comment by 39Delta** [comment]
@PlagueHO, Just merged in the latest changes and all is passing now.  Again thanks for your help!

**Comment by PlagueHO** [comment]
Hi @39Delta - this PR has conflicts now (due to previous one being merged). Can you resolve and I'll finish review on this one too. Thank you! 😀

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/249)* status: all files reviewed, 4 unresolved discussions (waiting on @39Delta)

___
*[CHANGELOG.md, line 18 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QE2X4oGF5J4UR-Bq:-MU7QE2X4oGF5J4UR-Br:bjqld76) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/CHANGELOG.md#L18)):*
> ```Markdown
> ### Changed
> 
> - Fix bug where `Import-PfxCertificateEx` would not install private keys in the ALLUSERSPROFILE path when importing to LocalMachine store. [Issue #248](https://github.com/dsccommunity/CertificateDsc/issues/248).
> ```

Can you split this line so that it doesn't go past about 100 chars?
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 167 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QQZj0s45H06_vUnu:-MU7QQZj0s45H06_vUnv:b5xjkku) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L167)):*
> ```PowerShell
>                 $importedCert = Get-ChildItem -Path ('Cert:\CurrentUser\My\{0}' -f $certificate.Thumbprint)
>                 $rsaKey = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($importedCert)
>                 $rsaKey.Key.IsMachineKey | Should -Be $false
> ```

Can you change this to ` | Should -BeFalse`

You can do this through the file if you like.
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 169 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QXx26q76D24v-thq:-MU7QXx26q76D24v-thr:b-v53snz) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L169)):*
> ```PowerShell
>                 $rsaKey.Key.IsMachineKey | Should -Be $false
>                 $importedCert.Thumbprint | Should -Be $certificate.Thumbprint
>                 $importedCert.HasPrivateKey | Should -Be $true
> ```

Can you change this to ` | Should -BeTrue`

You can do this through the file if you like.
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 212 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7RJgyAXP_oVuITO-b:-MU7RJgyAXP_oVuITO-c:bpmf5iv) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L212)):*
> ```PowerShell
>                         -Password $testCredential.Password
>                 } | Should -Throw 'Cannot export non-exportable private key.'
>                 $null = Remove-Item `
> ```

Could you add a blank line before this one?

**Review by 39Delta — COMMENTED** [review]
Made corrections per comments.  Let me know if there is anything else.  Thanks for your time!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-:-MU9Jtc-Dgu2_rdf6wCM:b-ybo55d)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 18 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QE2X4oGF5J4UR-Bq:-MU9JlaL9X9rz6PiyxsH:bsj646i) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/CHANGELOG.md#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you split this line so that it doesn't go past about 100 chars?
</blockquote></details>

Corrected.
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 167 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QQZj0s45H06_vUnu:-MU9Ji_0B9jJL6QSZZJh:b-69b478) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L167)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change this to ` | Should -BeFalse`

You can do this through the file if you like.
</blockquote></details>

Corrected all in file
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 169 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7QXx26q76D24v-thq:-MU9Jfn16ZPvUDg0mlWF:b-69b478) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L169)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change this to ` | Should -BeTrue`

You can do this through the file if you like.
</blockquote></details>

Corrected all in file
___
*[tests/Integration/CertificateDsc.Common.Tests.ps1, line 212 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-MU7RJgyAXP_oVuITO-b:-MU9JdOu2uDfr50CJsr1:b-8b11j9) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/e8b6caf40c0ffef85861da4eb6a0a0cf6f928871/tests/Integration/CertificateDsc.Common.Tests.ps1#L212)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line before this one?
</blockquote></details>

Added

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/249#-:-MUCODr66qdVwprS126a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
