### PR TITLE
CertReq: Add FriendlyName comparison

### LINKED ISSUE #121: Multiple certificates with the same name
For DSC MOF encryption and WinRM HTTPS all of my servers end up with 2 certificates. Unfortunately the method in which get xcertreg uses to determine if the cert already exists is simply the subject name and the CA's name. So when you have two certs with the same name but each has a different ability and unique friendly name the DSC gets very confused and keeps re-issuing certs. The common issue is here:

The certificate with subject 'CN=%hostnme%' issued by '%internal CA%' with thumbprint $Thumbprint has the wrong template $templatename.

We need to add something to the check routine beyond just the subject and the CA.

### PR DESCRIPTION
**Pull request by SwarfegaGit**
#### Pull Request (PR) description
Forgive me. I'm not a developer in the slightest but this simple comparison is working for me in my environment and fixes the issues seen in #121. 

#### This Pull Request (PR) fixes the following issues

Fixes #121

#### Task list

- [ ] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/206)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @SwarfegaGit  - are you still working on this one?

**Comment by SwarfegaGit** [comment]
Hi @PlagueHO.  Apologies for the late response.  No, I am not.  As per the original submission, I'm not a great coder and only added it to resolve an issue I was experiencing.  Unit testing etc is a bit beyond my skill level sorry :(

**Comment by PlagueHO** [comment]
No worries @SwarfegaGit - I'll see if I can incorporate it. The feature itself is easy enough, but it might be worth putting a switch in to control the behavior.

**Comment by PlagueHO** [comment]
This is superseded by #271 .

**Pull request closed without merging**
