### PR TITLE
add certreq basic error handling

### LINKED ISSUE #224: Occasional False Positive in Accepting certificate result logic
I've been investigating an intermittent issue with an older version of what was xCertificate, specifically 3.0.0.0 and stumbled across and error in the logic of the CertReq Set Functionality, particularly in the logic of the Accepting certificate result section.

This seems to stem from the following lines where there is no logic to inspect the output of the certreq  before blindly pushing that output further on. 
https://github.com/dsccommunity/CertificateDsc/blob/1784acc027cc848e06aa318abe28656f696a5d66/source/DSCResources/DSC_CertReq/DSC_CertReq.psm1#L668-L675

This particularly causes an issue where it can mean that the resource will show that it is in the desired state but in reality it is in a failed state.

An example output of the issue is as below.
```[[xCertReq]ADFS] Set-TargetResource: Accepting certificate result: Certificate Request Processor: A certificate chain processed but terminated in a root certificate which is not trusted by the trust provider. 0x800b0109 (-2146762487 CERT_E_UNTRUSTEDROOT)```

An Example Configuration where this will cause a false failing would be as below, when requesting a cert to then use that cert for ADFS, IIS etc etc 

```powershell
		$CertSubject = $PublicDNS
			xCertreq ADFS {
				DependsOn = '[xADUser]AdfsService'
				Subject = $CertSubject
				CAServerFQDN = $CAServerFQDN
				CARootName = $CARootName
				KeyLength = 1024
				KeyUsage = '0xa0'
				OID = '1.3.6.1.5.5.7.3.1'
				ProviderName = '"Microsoft RSA SChannel Cryptographic Provider"'
				CertificateTemplate = 'WebServer'
				AutoRenew = $true
				Exportable = $false
			}
			$AdfsDisplayName = $VMName + "Authentication"
			cADFSfarm AdfsConfigure {
				PsDscRunAsCredential = $DomainCredentialsAtDomain
				DependsOn = '[xCertReq]ADFS'
				Ensure = 'Present'
				ServiceCredential = $ServiceCredential
				InstallCredential = $DomainCredentials
				CertificateSubject = $CertSubject
				DisplayName = $AdfsDisplayName
				ServiceName = $CertSubject
			}
```

I would suggest adding in some logic to look at the output of certreq.exe and either fail the resource, or retry upto 5 times before failing the resource

### PR DESCRIPTION
**Pull request by kilasuit**
#### Pull Request (PR) description
Adds simple error handling for certreq call

#### This Pull Request (PR) fixes the following issues

Fixes #224
#### Task list

- [x] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/231)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks @kilasuit - can you add an entry to the CHANGELOG.md in the Unreleased section? Also, a recent breaking change to ModuleBuilder broke all the builds. So I've got to fix #230 before this one can go through. Will submit a PR for that shortly so your build can pass.

**Comment by PlagueHO** [comment]
@kilasuit - should be able to rebase now as the build pipeline fix PR is through.

**Comment by johlju** [comment]
@PlagueHO do you have time to review this one now when it passes the tests?

**Comment by kilasuit** [comment]
> Nitpick- can you add a full stop at the end?

So I tried this, a few different times and ways
it then broke the test 🤷‍♂️
so I had to remove that last fullstop

**Pull request merged**
